
{{ config(materialized='table') }}

SELECT 
    TO_DATE(O.CREATED_AT) CREATED_AT, 
    O.TOTAL_PRICE_USD, 
    COUNT(OL.ORDER_ID) COUNT_ORDER
FROM "FIVETRAN_DATABASE"."SHOPIFY_DS"."ORDER" AS O
JOIN "FIVETRAN_DATABASE"."SHOPIFY_DS"."ORDER_LINE" AS OL
ON O.ID = OL.ORDER_ID
GROUP BY TO_DATE(O.CREATED_AT), O.TOTAL_PRICE_USD