{{ config(materialized='table') }}

SELECT O.CREATED_AT,
(AVG(O.TOTAL_PRICE_USD)/COUNT(OL.ORDER_ID)) AVERAGE_ORDER_VALUE
FROM "FIVETRAN_DATABASE"."SHOPIFY_DS"."ORDER" AS O
JOIN "FIVETRAN_DATABASE"."SHOPIFY_DS"."ORDER_LINE" AS OL
ON O.ID = OL.ORDER_ID
GROUP BY O.CREATED_AT