
version: 2

models:
  - name: cleaned_order_line
    description: "A cleaner order line table"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
      - name: order_id
        description: "References the order table details"
      - name: product_id
        description: "References the products table details"
      - name: price
        description: "The Price of the product bought"
      - name: quantity
        description: "The quantity the customer bought"
      - name: TOTAL_DISCOUNT
        description: "Total discount customer given on the product."


  - name: top_selling_product_by_title
    description: "Shows top selling products"
    columns:
      - name: title
        description: "The product title"
        tests:
          - unique
          - not_null
      - name: created_at
        description: "The date the product was purchase."
      - name: total
        description: "Total amount of the product."

  - name: Sales_by_city
    description: "Shows the sales by city in the year 2022"
    columns:
      - name: created_at
        description: "The date the order was done."
  

